spring.application.name=pruebaTecnica-RESTAPI

# PostgreSQL
spring.datasource.url=jdbc:postgresql://localhost:5432/pedidosdb
spring.datasource.username=admin
spring.datasource.password=ps123
spring.datasource.driver-class-name=org.postgresql.Driver

# Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# PostgreSQL Dialect
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

# JWT
jwt.secret=TU_CLAVE_SUPER_SECRETA_DE_MINIMO_256_BITS

# Swagger
springdoc.api-docs.path=/api-docs
springdoc.swagger-ui.path=/swagger-ui.html

# Puerto
server.port=8080